### PR TITLE
Verbose pathdiff

### PR DESCRIPTION
**Pull request by gaballench**

### CODE REVIEW

**Comment by gaballench** [comment]
I'm so sorry, I did not intend to do this pull request to the main repo of hybrid-Lambda but rather to my own fork. Apologies for any inconvenience this might cause!

**Comment by shajoezhu** [comment]
Hi @gaballench , very sorry for the delay in replying. I just saw this message. would you want to keep this PR, I can review it?

**Comment by gaballench** [comment]
Hello @shajoezhu! In fact it was an unintended pull request, sorry for the inconvenience. Please feel free to ignore or delete it. The only thing that it does is to fail whenever a  network fails ultrametricity.

Best wishes,

Gustavo

**Comment by shajoezhu** [comment]
Ah I see. I will leave it as closed then. Thanks man

**Pull request closed without merging**
